// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv9EA1RuPo3acVXeT1FPcwpDOUajTNszw',
    appId: '1:804894967830:web:0bf8a7e1573070cb3e0d37',
    messagingSenderId: '804894967830',
    projectId: 'closetmate2025',
    authDomain: 'closetmate2025.firebaseapp.com',
    storageBucket: 'closetmate2025.firebasestorage.app',
    measurementId: 'G-CNGDWZX83S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGUyvLIo1VVLhEyHTpfNVScpGmC-7mBbs',
    appId: '1:804894967830:android:9cd753a6480502d93e0d37',
    messagingSenderId: '804894967830',
    projectId: 'closetmate2025',
    storageBucket: 'closetmate2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0dm1tVu_U1Olbpivi7a3Dhk3QLA5DRe4',
    appId: '1:804894967830:ios:57b9c350bafedc4d3e0d37',
    messagingSenderId: '804894967830',
    projectId: 'closetmate2025',
    storageBucket: 'closetmate2025.firebasestorage.app',
    iosBundleId: 'com.example.closetMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0dm1tVu_U1Olbpivi7a3Dhk3QLA5DRe4',
    appId: '1:804894967830:ios:57b9c350bafedc4d3e0d37',
    messagingSenderId: '804894967830',
    projectId: 'closetmate2025',
    storageBucket: 'closetmate2025.firebasestorage.app',
    iosBundleId: 'com.example.closetMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv9EA1RuPo3acVXeT1FPcwpDOUajTNszw',
    appId: '1:804894967830:web:dc17561860730d703e0d37',
    messagingSenderId: '804894967830',
    projectId: 'closetmate2025',
    authDomain: 'closetmate2025.firebaseapp.com',
    storageBucket: 'closetmate2025.firebasestorage.app',
    measurementId: 'G-X2G5FV1YM5',
  );
}
